title: Affiliate Links
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:

        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS

          fields:
            publishing:
              type: section
              title: PLUGIN_ADMIN.PUBLISHING
              underline: true

              fields:
                header.affiliation:
                  unset@: true

        affiliate-links:
          type: tab
          title: Affiliate Links

          fields:

            header.affiliate-links.enabled:
              type: select
              label: Enabled
              size: medium
              options:
                website: Website (default)
                enabled: Enabled for this article
                disabled: Disabled for this article
              validate:
                required: true

            header.affiliate-links.affiliation:
              name: affiliation
              type: list
              style: vertical
              label: Links

              fields:

                .link_type: 
                   type: select
                   label: 'Affiliation provider'
                   size: short
                   help: 'Copy the image URL link here, not text only nor text+image link'
                   data-options@: '\Grav\Plugin\AffiliateLinksPlugin::allowedProviders' 
                .link_help:
                   type: display
                   size: large
                   label: Instructions
                   markdown: true
                   content: "Copy the image link URL here. **Do not** copy the text only URL or image+text URL..."
                .link_url:
                   type: text
                   label: 'Image link URL'
                .link_desc:
                   type: text
                   help: "Alternative description (replacing link's decription if not empty)"
                   label: 'Opt. description'


